name: proto_x_gen
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.14.3 <3.0.0"

dependencies:
  change_case: ^1.0.1
  dart_style: ^2.2.0
  proto_x: ^0.0.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

dependency_overrides:
  proto_x:
    path: ../proto_x
