name: proto_x_gen
description: A simple command-line application.
version: 0.0.1-pre
# homepage: https://www.example.com

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  args: ^2.3.0
  change_case: ^1.0.1
  dart_style: ^2.2.0
  glob: ^2.0.2
  proto_x: ^0.0.1-pre

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

dependency_overrides:
  proto_x:
    path: ../proto_x
