name: lsp
description: A starting point for Dart libraries or applications.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  async: ^2.7.0
  built_collection: ^5.1.0
  built_value: ^8.1.1
  json_rpc_2: ^3.0.1
  stream_channel: ^2.1.0
  web_socket_channel: ^2.1.0

dev_dependencies:
  build_runner: ^2.0.6
  built_value_generator: ^8.1.1
  lints: ^1.0.1
  test: ^1.16.0
