name: proto_x
description: A starting point for Dart libraries or applications.
version: 0.0.1-pre
# homepage: https://www.example.com

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  built_collection: ^5.1.0
  built_value: ^8.1.1
  collection: ^1.15.0
  source_span: ^1.8.1
  string_scanner: ^1.1.0

dev_dependencies:
  build_runner: ^2.0.6
  built_value_generator: ^8.1.1
  lints: ^1.0.1
  test: ^1.16.0
